###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/11

###
Patch http://localhost:3000/users/0c7602ba-5686-4969-8d89-ca1e0304e502
Content-Type: application/json

{
  "apartment": "302",
  "name":"Dionathan",
  "email": "dionathan.cordova3@gmail.com",
  "telephone": "47 9 9999-9999",
  "password": "teste",
  "permission_id": 0,
  "avatar": "null",
  "condominium_id": 7,
  "is_admin": false,
  "can_show_data": false
}

###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "apartment": "302",
  "name":"Dionathan2",
  "email": "dionathan.cordova@gmail.com",
  "telephone": "47 9 9999-9999",
  "password": "teste",
  "permission_id": 0,
  "avatar": "null",
  "condominium_id": 7,
  "is_admin": false,
  "can_show_data": true
}


###
Delete http://localhost:3000/users/f6e2d70c-4046-4ae7-abc3-ff0295c480d5
