###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/11

###
PUT http://localhost:3000/users/09fa562c-3667-4230-a807-fe3baf39d778
Content-Type: application/json

{
  "apartment": 302,
  "name":"Dionathan",
  "email": "dionathan.cordova@gmail.com",
  "telephone": "47 9 9999-9999",
  "password": "teste",
  "permission_id": 0,
  "avatar": "null",
  "condominium_id": 7,
  "is_admin": false,
  "can_show_data": false
}

###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "apartment": 302,
  "name":"Dionathan2",
  "email": "dionathan.cordova2@gmail.com",
  "telephone": "47 9 9999-9999",
  "password": "teste",
  "permission_id": 0,
  "avatar": "null",
  "condominium_id": 7,
  "is_admin": false,
  "can_show_data": true
}


###
Delete http://localhost:3000/users/391
