###
GET http://localhost:3000/cond-config/7908401d-acfa-4925-9721-4af175dd1b13


###
GET http://localhost:3000/cond-config/7908401d-acfa-4925-9721-4af175dd1b13/last

### 
POST http://localhost:3000/cond-config  HTTP/1.1
Content-Type: application/json

{
    "basic_water_rate": 9,
    "average_water_rate": 10,
    "high_water_rate": 11,
    "cleaning_fee": 250,
    "reserve_value": 300,
    "m3_gas_value": 19,
    "liquidator_exempt": false,
    "payment_plan": "free",
    "year": 2020,
    "condominium_id": "7908401d-acfa-4925-9721-4af175dd1b13"
}

### 
PATCH  http://localhost:3000/cond-config/0b1c080d-ca32-4daa-aea8-8de45f84dc34  HTTP/1.1
Content-Type: application/json

{
    "basic_water_rate": 9,
    "average_water_rate": 10,
    "high_water_rate": 11,
    "cleaning_fee": 250,
    "reserve_value": 300,
    "m3_gas_value": 19,
    "liquidator_exempt": false,
    "payment_plan": "pay-to-play",
    "year": 2021,
    "condominium_id": "7908401d-acfa-4925-9721-4af175dd1b13"
}